# Версия docker-compose
# В prod используем именованные тома, т.к. код менять не собираемся
version: '3'
# Список наших сервисов (контейнеров)
services:
    nginx:
        # собираем nginx из Dockerfile-nginx-... в текущей папке с указанием типа среды dev или prod из файла .env
        build:
            context: .
        image: fe-nginx-${{ env.ENV_TYPE }}
        # маршрутизируем порты
        ports:
            - "80:80"
        container_name: fe-nginx-${{ ENV_TYPE }}