# Для начала указываем исходный образ, он будет использован как основа
FROM php:7.4-fpm-alpine

# RUN выполняет идущую за ней команду в контексте нашего образа.
# В данном случае мы установим некоторые зависимости и модули PHP.
# Для установки модулей используем команду docker-php-ext-install.
RUN apk add \
        curl \
	stress-ng \
	libzip-dev \
	libmcrypt-dev \
        && docker-php-ext-install -j$(nproc) iconv mysqli pdo_mysql zip

# Куда же без composer'а.
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

ARG ENV_TYPE

# Добавим свой php.ini, можем в нем определять свои значения конфига
COPY php.ini.$ENV_TYPE /usr/local/etc/php/conf.d/40-custom.ini

# Копируем исходники в контейнер
COPY ./api /var/www/api

COPY api/config/settings.$ENV_TYPE /var/www/api/config/settings.ini

# Указываем рабочую директорию для PHP
WORKDIR /var/www

# Запускаем контейнер
CMD ["php-fpm"]
