apiVersion: v1
kind: Service
metadata:
  name: fe-nginx
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: fe-nginx
---
apiVersion: v1
kind: Service
metadata:
  name: php
spec:
  type: ClusterIP
  ports:
  - name: php
    port: 9000
  selector:
    app: be-php
---
apiVersion: v1
kind: Service
metadata:
  name: be-nginx
spec:
  type: ClusterIP
  ports:
  - name: be-nginx
    port: 8080
    targetPort: 80
  selector:
    app: be-nginx
